[project]
name = "importer"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "mwxml>=0.3.4",
    "meilisearch>=0.33.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
